# Generated by Django 4.2 on 2023-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
                ("deleted", models.BooleanField()),
                ("name", models.CharField(max_length=20)),
                ("title", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
