# Generated by Django 4.2 on 2023-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_table_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="table",
            name="title",
        ),
        migrations.AddField(
            model_name="table",
            name="fields",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
